### ISSUE TITLE
Hat tip

### ISSUE THREAD

**Issue by floe** [WolfsHollow/WordMaster#1]
Thank you for creating a Wordle clone that doesn't require me to install NPM and one gazillion packages, run everything through 17 preprocessing steps, and load some dozens of external resources. The JavaScript ecosystem is so fucked up. [/rant]

FTR, I've forked your code to create a Swabian clone of Wordle: https://github.com/floe/woertle (I imagine that won't help you much, but anyway, thanks again ;-)

**Comment by floe** [comment]
BTW, would you mind to add a LICENSE file?

**Comment by WolfsHollow** [comment]
Added a license file. Thank you. 

I think the reason everyone has so many things added onto it is for the guess validation. Right now this main branch does not check if the word you are inputting is a word. I have one in the serverWorking branch that requires server use, but haven't figured out how to do it in a different way quite yet. I'll need to play around with it more.

As of now, I'll be adding seed support to be able to 'share' words.
